name: Run tests

on: [ push, pull_request ]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ 7.3, 7.4, 8.0 ]
                laravel: [ 6.*, 7.*, 8.* ]
                dependency-version: [ prefer-stable ]
                include:
                    -   testbench: 6.*
                        laravel: 8.*
                    -   testbench: 5.*
                        laravel: 7.*
                    -   testbench: 4.*
                        laravel: 6.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: pdo, sqlite, pdo_sqlite
                    coverage: pcov

            -   name: Install dependencies
                run: |
                    composer require "illuminate/database:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
